{
  "file": "core/src/error.rs",
  "name": "<error::Source<'_> as iter::traits::iterator::Iterator>::next",
  "hash": "20834170844971538868192273210386265911",
  "hash_direct": "183575760704797376916691513150516252460",
  "src": "fn next(&mut self) -> Option<Self::Item> {\n        let current = self.current;\n        self.current = self.current.and_then(Error::source);\n        current\n    }",
  "callees": [
    "1251782662895651911114429423970888599104",
    "1244815220159457112782545385940262871",
    "60223182454201538031385000853448716574"
  ]
}
